language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tshala/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tshala/react-test npm test

after_success:
    - docker build -t tshala/multi-client ./client
    - docker build -t tshala/multi-nginx ./nginx 
    - docker build -t tshala/multi-server ./server
    - docker build -t tshala/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push tshala/multi-client
    - docker push tshala/multi-nginx
    - docker push tshala/multi-server
    - docker push tshala/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-573057936035
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY